apiVersion: harness.io/v1
kind: Component
type: service
identifier: TestAccResourceRemoteCatalogEntity_QbcTI_base
name: Base Branch Catalog Entity
owner: user:account/admin@harness.io
orgIdentifier: default
projectIdentifier: SSEM
spec:
  lifecycle: prod
metadata:
  description: Base branch fixture for TestAccResourceRemoteCatalogEntity_QbcTI
